#
## DB : MySQL
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.datasource.url=jdbc:mysql://127.0.0.1:3306/momo_db?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
##spring.datasource.username=root
##spring.datasource.password=0000
#
#
#spring:
#  # mybatis logging
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/momo_db?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 0000
#  # Thymeleaf
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: html
#    check-template-location: true
#    enabled: true
#    cache: false
#  web:
#    resources:
#      add-mappings: true
#      # MIME ?? ??? ??
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: classpath:/
#  # Email API (SMTP)
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: km1104rs@gmail.com
#    password: fagrbmmkmidrobca
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#
## Mybatis
#mybatis:
#  mapper-locations: mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#
## ?
#server:
#  servlet:
#    encoding:
#      force: true
#
#
#file:
#  dir: classpath:/storage
#
#
#
#
